name: CI
on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17.3
          otp-version: 27.1.1

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Run CI
        run: task ci
